# Generated by Django 3.2.19 on 2023-06-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_userinput'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
