# Generated by Django 3.2.19 on 2023-06-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_question_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='seed_statements',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
    ]
