# Generated by Django 3.2.19 on 2023-06-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_question_seed_statements'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollResults',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When this instance was created.')),
                ('modified', models.DateTimeField(auto_now=True, help_text='When this instance was modified.')),
                ('cluster', models.CharField(max_length=200)),
                ('statement', models.TextField(blank=True, help_text='Statement that this cluster represents')),
                ('total_users', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='question',
            name='seed_statements',
        ),
        migrations.RemoveField(
            model_name='userinput',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='userinput',
            name='statement_shown_to_user',
        ),
        migrations.AddField(
            model_name='userinput',
            name='flag_seed_statement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinput',
            name='score',
            field=models.IntegerField(default=25, help_text='Meta field for storing score for this statement.'),
        ),
        migrations.AddField(
            model_name='userinput',
            name='statement',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
