# Generated by Django 3.2.19 on 2023-06-23 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20230623_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinput',
            name='flag_seed_statement',
        ),
        migrations.RemoveField(
            model_name='userinput',
            name='score',
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When this instance was created.')),
                ('modified', models.DateTimeField(auto_now=True, help_text='When this instance was modified.')),
                ('statement', models.TextField()),
                ('score', models.IntegerField(default=25, help_text='Meta field for storing score for this statement.')),
                ('flag_seed_statement', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='userinput',
            name='statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.statement'),
        ),
    ]
